import { type Component } from 'solid-js';
import { type IconProps } from './common/utils';

export type { IconProps };
export type Icon = Component<IconProps>;

export { IconAsteroid } from './asteroid';
export { IconBack } from './back';
export { IconChevronRight } from './chevron-right';
export { IconCity } from './city';
export { IconCloud } from './cloud';
export { IconContext } from './context';
export { IconCopy } from './copy';
export { IconCross } from './cross';
export { IconCurtainExpand } from './curtain-expand';
export { IconEyeCog } from './eye-cog';
export { IconEye } from './eye';
export { IconFlag } from './flag';
export { IconG } from './g';
export { IconGalaxy } from './galaxy';
export { IconGasGiant } from './gas-giant';
export { IconLeaf } from './leaf';
export { IconMoon } from './moon';
export { IconOrbit } from './orbit';
export { IconPeople } from './people';
export { IconPlanet } from './planet';
export { IconPlotOutline } from './plot-outline';
export { IconPlot } from './plot';
export { IconPressure } from './pressure';
export { IconRadius } from './radius';
export { IconRocks } from './rocks';
export { IconShip } from './ship';
export { IconSpaceStation } from './space-station';
export { IconStar } from './star';
export { IconSystem } from './system';
export { IconTemperature } from './temperature';
export { IconText } from './text';
export { IconUnknown } from './unknown';
export { IconUser } from './user';
